"""Dynamic CrewAI crew file generator."""

import os
from typing import Any

import httpx
from jinja2 import Template


CREW_TEMPLATE = '''"""{{ crew_name }} Crew — Auto-generated by CO-CEO Agent."""

from typing import Any

from crews.base import BaseCrew


class {{ class_name }}(BaseCrew):
    DESCRIPTION = "{{ description }}"
    AGENT_NAMES = {{ agent_names }}

    def kickoff(self, inputs: dict[str, Any]) -> dict[str, Any]:
        topic = inputs.get("topic", "{{ default_topic }}")
        results = {}
        total_cost = 0.0
        last_model = "unknown"

        {% for agent in agents %}
        # Agent {{ loop.index }}: {{ agent.role }}
        prompt_{{ loop.index }} = (
            "You are a {{ agent.role }}. {{ agent.goal }}\\n\\n"
            "Topic: " + topic + "\\n"
            {% if loop.index > 1 %}
            "Previous context:\\n" + str(list(results.values())[-1].get("text", ""))[:2000] + "\\n\\n"
            {% endif %}
            "Provide your output as structured JSON."
        )
        result_{{ loop.index }} = self._llm_call(
            prompt_{{ loop.index }},
            system_prompt="{{ agent.backstory }}",
        )
        results["{{ agent.role | lower | replace(' ', '_') }}"] = result_{{ loop.index }}
        total_cost += result_{{ loop.index }}.get("cost", 0)
        last_model = result_{{ loop.index }}.get("model", "unknown")
        {% endfor %}

        return {
            "crew": "{{ crew_name }}",
            **{k: v["text"] for k, v in results.items()},
            "cost": total_cost,
            "model": last_model,
            "agents_used": self.AGENT_NAMES,
        }
'''


class CrewCreator:
    """Generates new CrewAI crew Python files dynamically."""

    def __init__(self, router: Any):
        self.router = router

    async def create(self, crew_name: str, description: str, agents: list[dict]) -> dict:
        """Generate a new crew file and optionally restart the CrewAI service."""
        class_name = "".join(w.capitalize() for w in crew_name.split("_")) + "Crew"
        agent_names = [a.get("role", f"Agent {i+1}") for i, a in enumerate(agents)]

        template = Template(CREW_TEMPLATE)
        code = template.render(
            crew_name=crew_name,
            class_name=class_name,
            description=description,
            agent_names=agent_names,
            agents=agents,
            default_topic=description.split()[0] if description else "general",
        )

        crew_file_path = f"/app/crews/{crew_name}.py"
        try:
            os.makedirs(os.path.dirname(crew_file_path), exist_ok=True)
            with open(crew_file_path, "w") as f:
                f.write(code)
            file_written = True
        except Exception as exc:
            file_written = False
            code = f"# Could not write file: {exc}\n{code}"

        return {
            "crew_name": crew_name,
            "class_name": class_name,
            "agents": agent_names,
            "file_path": crew_file_path,
            "file_written": file_written,
            "code": code,
            "message": f"Crew '{crew_name}' created with {len(agents)} agents",
        }
