"""Template for dynamically generating CrewAI crew files."""

CREW_FILE_TEMPLATE = '''"""{{ crew_name }} Crew — Auto-generated by CO-CEO Agent."""

from typing import Any
from crews.base import BaseCrew


class {{ class_name }}(BaseCrew):
    DESCRIPTION = "{{ description }}"
    AGENT_NAMES = {{ agent_names }}

    def kickoff(self, inputs: dict[str, Any]) -> dict[str, Any]:
        topic = inputs.get("topic", "general")
        results = {}
        total_cost = 0.0
{% for agent in agents %}
        # Agent {{ loop.index }}: {{ agent.role }}
        result_{{ loop.index }} = self._llm_call(
            "You are a {{ agent.role }}. {{ agent.goal }}\\n"
            "Topic: " + topic,
            system_prompt="{{ agent.backstory }}",
        )
        results["{{ agent.key }}"] = result_{{ loop.index }}
        total_cost += result_{{ loop.index }}.get("cost", 0)
{% endfor %}
        return {
            "crew": "{{ crew_name }}",
            **{k: v["text"] for k, v in results.items()},
            "cost": total_cost,
            "model": list(results.values())[-1].get("model", "unknown"),
            "agents_used": self.AGENT_NAMES,
        }
'''
